server:
  port: 10011
spring:
  application:
    name: tensquare‐manager 
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
zuul:
  routes:
    tensquare-base:  #基础
      path: /base/**  #配置请求URL的请求规则
      serviceId: tensquare-base  #指定Eureka注册中心中的服务id
    tensquare-article:  #文章
      path: /article/**
      serviceId: tensquare-article
    tensquare-qa:  #问答
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:  #招聘
       path: /recruit/**
       serviceId: tensquare-recruit
    tensquare‐search: #搜索
      path: /search/**
      serviceId: tensquare-search
    tensquare-sms:
      path: /sms/**
      serviceId: tensquare-sms
    tensquare-spit:  #吐槽
      path: /spit/**
      serviceId: tensquare-spit
    tensquare-user:  #用户
      path: /user/**
      serviceId: tensquare-user
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
jwt:
  config:
    key: zeus
