server: 
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_qa
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
feign:
  hystrix:
    enabled: true



