server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
